### ISSUE TITLE
Page navigation error with sidepanel

### ISSUE THREAD

**Issue by masterprogrammer513** [phonon-framework/phonon#235] opened 2017-03-17 14:12 UTC
If side panel is enabled page navigation give me this error

mycode:
Index.html contain : 
`<div class="side-panel side-panel-right" data-expose-aside="right" data-disable="left" data-page="dashboard,profile,sandogh,charge" id="sideMenu">
    </div>`

Error at line 
 settings.element.removeChild(backdrop);

Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLDivElement.e

**Comment by Qathom** [comment] 2017-03-18 13:42
Hi @cinohee,

Thank you for opening this issue.
I can't reproduce your bug.. Can you please give me more information?
Such as the OS, browser and what you did to get this error.

**Comment by cinohee** [comment] 2017-03-18 15:12
Hi @Qathom 
This is my Index file
rename to html file
I load data by Ractive to menu.
Is there any problem in my file?

[index.txt](https://github.com/quark-dev/Phonon-Framework/files/852524/index.txt)

**Comment by kraenzel** [comment] 2017-12-20 08:38
Hello 
I have the same problem.  The Exception is raised when navigating to a new page.
In the function `removeBackdrop` the settings.element points to the new page but
the backdrop is not a child of that page.

In  `removeBackdrop` I changed the line
`settings.element.removeChild(backdrop);`
to
`backdrop.parentElement.removeChild(backdrop);`
which solved the problem for me.

**Comment by qathom** [comment] 2019-07-22 19:07
Hi all,

This issue should be fixed with v1.5.1.
Hence I'm closing this ticket. Feel free to reopen this one if v1.5.1 doesn't fix your error.

**Closed by qathom** 2019-07-22 19:07 UTC
Labels: help wanted, improvement
